export const OPEN_MODAL = 'OPEN MODAL'
export const CLOSE_MODAL = 'CLOSE MODAL'
export const OPEN_EDIT_FORM = 'OPEN EDIT FORM'
export const CLOSE_EDIT_FORM = 'CLOSE EDIT FORM'
export const OPEN_DIALOG = 'OPEN DIALOG'
export const CLOSE_DIALOG = 'CLOSE DIALOG'
export const DELETE_USER = 'DELETE USER'
